language: go
go:
- "1.11.x"
install: true
script:
- env GO111MODULE=on go build
- env GO111MODULE=on go test
before_deploy:
- GO111MODULE=on GOOS=linux   GOARCH=amd64 go build -o ndm_linux_amd64
- GO111MODULE=on GOOS=linux   GOARCH=386   go build -o ndm_linux_386
- GO111MODULE=on GOOS=linux   GOARCH=arm   go build -o ndm_linux_arm
- GO111MODULE=on GOOS=darwin  GOARCH=amd64 go build -o ndm_darwin_amd64
- GO111MODULE=on GOOS=windows GOARCH=amd64 go build -o ndm_windows_amd64.exe
- GO111MODULE=on GOOS=windows GOARCH=386   go build -o ndm_windows_386.exe
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WlVVhWs9FOJQnPg1RE+/rgYw+xVgL55A3aqlkkUyjYihBpQNf2FKKdHO6vX9G15pvAkRKjqvMfyjRVtnIe2Qwva/NOdZS3lB11WX+dv+AGitkag6xoPyB1xu3AtWQKX5pgtlxnKVfKRqF//+gnwq2ydT9VEzKYTZLrf37nFOG0OPYkB9ORGnrGRLR7NH1p9gvRbiEk/8QZNkgVh2tengrR6FrcyNS3SuIA2XzMCjnLB4dI0LANwgD46ygUmTk+VmClF/PGEz8CCt6hHWB+8rPwbVW7VEKlgpbwYlDyLI7qgA7RG18tLGilXhc13J8lS4SCFOi8beTu2KvcmQ8scI9f9OlD8izdZ6W+9Ma/moJ1AXLgDLANHGRzYCOe8sF4oJBIySgkGa4DY6Wsy9dIQ/c5FDnpAOA4KJp3jKL15X68wfAbI68PjbqmZXYvvCQvggLhlYYxFkvUOhD0IJaVI5x2wzZJSlUZKZJCO6ToDTiPBpPjGp9vAJvVZDHSoYWaPn0IS8GCeg5JotdwPeOMmBSetMGQ5rFmen9r0DN9aOY+hcrGzoD3MeTkbp7RfsJlcUXknieEsIQvfObcj2S9USYvGK1Omv53zTUCrQXzPgGP7q696ev0ER83HMpIUNj1/8ohevruDsiEzDL/DNb9BmVCZO2Kd+C4DkPChdli823pE=
  file:
  - ndm_linux_amd64
  - ndm_linux_386
  - ndm_linux_arm
  - ndm_darwin_amd64
  - ndm_windows_amd64.exe
  - ndm_windows_386.exe
  on:
    tags: true
    repo: samhug/ndm
